# Библиотека NumPy

In [5]:
import numpy as np

## Работа с матрицами

**1. Создайте две матрицы размером 2x2: одна заполнена единицами, другая - нулями.**

In [6]:
matrix_ones = np.ones((2, 2)) # Аргумент (2, 2) определяет размерность матрицы: 2 строки, 2 столбца.
matrix_zeros = np.zeros((2, 2))

print(matrix_ones)
print(matrix_zeros)


[[1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]]


Так же, вместо np.ones, np.zeros можно использовать np.full, принимающий два аргумента - размер матрицы и число, которым нужно заполнить матрицу.

In [7]:
matrix_ones = np.full((2, 2), 1)
matrix_zeros = np.full((2, 2), 0)

print(matrix_ones)
print(matrix_zeros)

[[1 1]
 [1 1]]
[[0 0]
 [0 0]]


**2.  Создайте две матрицы размером 2x2 с произвольными числами и выполните их сложение и вычитание.**

In [25]:
import numpy as np
matrix_A = np.array([[1, 5], 
                     [4, 9]])
matrix_B = np.array([[9, 8], 
                     [3, 0]])

matrix_С = matrix_A + matrix_B
matrix_D = matrix_B - matrix_A

print(matrix_С)
print(matrix_D)


[[10 13]
 [ 7  9]]
[[ 8  3]
 [-1 -9]]


**Важно**: для выполнения сложения и вычитания матрицы должны иметь одинаковые размеры, иначе возникнет ошибка!

**Важно**: если поменять матрицы местами при вычитании, результат будет другим!

In [26]:
matrix_D = matrix_B - matrix_A
print(matrix_D)
matrix_D = matrix_A - matrix_B
print(matrix_D)

[[ 8  3]
 [-1 -9]]
[[-8 -3]
 [ 1  9]]


**3.  Создайте две матрицы 2x2 и выполните матричное умножение.**

In [ ]:
import numpy as np

matrix_A = np.array([[2, 3], 
                     [1, 4]])
matrix_B = np.array([[5, 2], 
                     [3, 6]])

matrix_C = matrix_A * matrix_B # Поэлементое умножение
matrix_D = np.dot(matrix_A, matrix_B) # Матричное умножение, вместо np.dot можно использовать символ @ -> matrix_A @ matrix_B
print(matrix_C)
print(matrix_D)

[[10  6]
 [ 3 24]]
[[19 22]
 [17 26]]


**Важно**: при матричном умножении важен порядок множителей!

In [ ]:
matrix_D = matrix_A @ matrix_B
print(matrix_D)
matrix_D = matrix_B @ matrix_A
print(matrix_D)

[[19 22]
 [17 26]]
[[12 23]
 [12 33]]


**Важно**: размеры матриц должны совпадать!

**4. Создайте квадратную матрицу 3x3 и найдите её транспонированную матрицу и определитель.**

In [32]:
import numpy as np
matrix_A = np.array([[1, 2, 3], 
                     [4, 5, 6], 
                     [7, 8, 9]])

transponsed_matrix = np.transpose(matrix_A) 
determinant = np.linalg.det(transponsed_matrix)
print(transponsed_matrix)
print(determinant)



[[1 4 7]
 [2 5 8]
 [3 6 9]]
0.0


**5.  Создайте квадратную матрицу 3x3 и найдите её обратную матрицу (если это возможно).**

In [48]:
import numpy as np
matrix_A = np.array([[3, 2, 3], 
                     [4, 5, 6], 
                     [7, 8, 9]])

determinant = np.linalg.det(matrix_A)

if abs(determinant) == 0:
    print("Обратной матрицы не существует")
else:
    inverse_matrix = np.linalg.inv(matrix_A)
    print(inverse_matrix)

[[ 0.5        -1.          0.5       ]
 [-1.         -1.          1.        ]
 [ 0.5         1.66666667 -1.16666667]]


**Важно**: обратная матрица существует, если определитель матрицы не равен 0

Если исходную матрицу умножить на обратную матрицу - получится единичная матрица.

In [49]:
matrix = np.dot(matrix_A, inverse_matrix)
print(matrix)

[[ 1.00000000e+00  0.00000000e+00  4.44089210e-16]
 [-2.22044605e-16  1.00000000e+00  8.88178420e-16]
 [-1.11022302e-16  8.88178420e-16  1.00000000e+00]]


**6.  Решите систему линейных уравнений из 3 уравнений с 3 неизвестными, используя numpy.**

2x + 3y - z = 5

4x - y + 2z = 3

x + 2y + 3z = 4

In [59]:
import numpy as np

A = np.array([[2, 3, -1],
             [4, -1, 2], 
             [1, 2 ,3]])

B = np.array([5, 3, 4])

X = np.linalg.solve(A, B)

print(X)

[0.90566038 1.1509434  0.26415094]


В матричной форме: A·X = B, где:

A - матрица коэффициентов

X - вектор неизвестных [x, y, z]

B - вектор правых частей

**7.  Найдите собственные значения и собственные векторы для квадратной матрицы 3x3.**

In [63]:
import numpy as np

matrix = np.array([[4, 2, 1],
                   [3, 5, 6],
                   [2, 1, 8]])

eigenvalues, eigenvectors = np.linalg.eig(matrix)

print(eigenvalues)
print(eigenvectors)

[10.55002114  2.55568373  3.89429513]
[[-0.31942971 -0.83966449 -0.86426287]
 [-0.76990889  0.49786632 -0.1876806 ]
 [-0.55245358  0.21700846  0.46671799]]


## Генерация случайных чисел

**1. Сгенерируйте массив из 10 случайных чисел в диапазоне [0, 1) и массив из 10 чисел в диапазоне [5, 10).**

In [109]:
import numpy as np

array_A = np.random.random(10) # Принимает на вход один аргумент - количество чисел, которые нужно сгенерировать. Генерирует числа [0, 1)
array_B = np.random.uniform(5, 10, 10) # На вход поступает - диапазон чисел [x, y), количество чисел
print(array_A)
print(array_B)


[0.8601753  0.75400321 0.89119787 0.16414008 0.19815491 0.8870832
 0.87392854 0.57198803 0.8980989  0.81003314]
[8.84644153 7.9126774  8.19502007 5.82191924 8.03206235 7.29552559
 7.17879684 5.44856514 8.18082721 5.57814367]


**2. Сгенерируйте массив из 20 случайных целых чисел в диапазоне от 1 до 100.**

In [128]:
import numpy as np

array_A = np.random.randint(0, 101, 20) # На вход поступает - диапазон чисел [x, y), количество чисел
print(array_A)

[96 89 23 75 47 30 88 87 62 96 93 54 15 75 47  7 17 10 27  0]


**3. Сгенерируйте 100 чисел из нормального распределения с mean=0 и std=1. Посчитайте среднее и стандартное отклонение сгенерированных данных.**

In [168]:
import numpy as np

normal_data = np.random.randn(100)

sample_mean = np.mean(normal_data)
sample_std = np.std(normal_data)

print(normal_data)
print(f"Среднее распределение {sample_mean}")
print(f"Стандартное отклонение {sample_std}")

[ 3.42285773e-02 -1.69112791e-01 -5.94029980e-01  3.45066833e+00
  2.26860365e-01  1.67541026e+00  7.53563997e-01  1.69299662e+00
 -1.82263515e+00  1.02867540e+00 -4.44696650e-04  2.14877072e+00
  7.24352458e-01  3.73001396e-01  1.00705802e+00  2.12713341e+00
 -1.66110376e-01  3.87336145e-01 -7.82627721e-01 -3.26802859e-01
  1.57672877e-02 -9.99826130e-01  2.09406514e+00 -8.59328387e-01
  4.63356540e-01 -3.35121516e-01  1.98988237e-01  6.67548009e-01
 -3.91111173e-02  2.88050683e-01  1.73261270e+00 -3.29144060e-01
  1.37638492e-01  2.17917758e+00 -6.00911220e-02 -8.29909703e-01
 -9.29625493e-01  5.24647050e-01 -7.51114150e-01 -2.13832811e-01
 -9.48839616e-01  5.06886439e-01  1.04486278e+00  8.16269360e-01
  1.74062605e-01  1.33695900e+00  8.12892173e-01 -4.92301825e-01
  3.22582351e-01  2.01987013e+00  1.03052103e-01  1.18844611e+00
  1.80631249e-01 -1.01401492e+00 -1.15420022e+00  9.14914666e-01
  7.08228655e-01  8.42751657e-01 -1.07303051e-01 -9.44781708e-01
  4.92522570e-02 -6.91586

**Нормальное распределение** — это особый тип распределения, при котором большинство значений сосредоточено около среднего. Его также называют гауссовым распределением, законом Гаусса или колоколообразным распределением, а его график — кривой Гаусса, или гауссианой.

**Mean (Среднее арифметическое, μ или x̄)** -  математическое ожидание выборки. Оценка центра распределения, которая минимизирует сумму квадратов отклонений от себя.

**Std (Standard Deviation, Среднеквадратическое отклонение, σ или s)** -  мера рассеяния значений случайной величины относительно её математического ожидания (mean)

**4. Cоздайте массив [1, 2, 3, 4, 5] и сделайте из него случайную выборку из 10 элементов (с повторениями).**

In [8]:
import numpy as np

array_A = np.array([1, 2, 3, 4, 5])

array_B = np.random.choice(array_A, 10)
print(array_B)

[5 1 2 2 5 3 5 3 4 4]


**5. Сгенерируйте случайную перестановку для массива [1, 2, 3, 4, 5, 6, 7, 8, 9, 10].**

In [236]:
import numpy as np

array_A = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

array_B = np.random.permutation(array_A)
print(array_B)

[ 5  7  2  4  8 10  3  6  9  1]


**6. Сгенерируйте матрицу 5x5 из нормального распределения с mean=0, std=1.**

In [239]:
import numpy as np

matrix = np.random.randn(5, 5)
print(matrix)

[[-0.79824842  0.84856485  1.10292905  0.48767691  1.28061228]
 [-2.52650377 -2.02327664  0.06943762 -1.07256698 -1.42856096]
 [ 0.91142527  0.48312918  1.76802817 -0.70589566  0.11782725]
 [-2.5805256  -0.34816947  0.35980437 -0.14320911  0.0209786 ]
 [ 0.15402059  0.61596934  1.76873508 -1.12745844 -0.82865901]]


**7. Сгенерируйте 1000 случайных чисел по биномиальному распределению с параметрами n=10 и p=0.5.**

In [ ]:
import numpy as np

array_A = np.random.binomial(10, 0.5, 1000) # Поступает три значения на вход: количество испытаний в одном эксперименте, вероятность успеха в одном испытании и последнее - общее число экспериментов.

print(array_A)

[ 4  5  3  6  5  4  6  5  6  4  7  3  4  4  5  5  5  6  4  5  3  5  7  7
  5  5  4  9  6  3  4  6  3  2  5  7  4  7  5  5  6  9  5  5  6  4  4  6
  7  3  5  6  5  3  4  5  3  6  7  6  4  7  8  5  5  5  3  5  5  5  2  5
  7  5  5  5  6  4  5  3  5  4  5  3  7  4  6  6  7  3  4  7  5  4  6  6
  6  6  5  3  6  5  4  5  5  6  8  8  2  5  3  6  5  6  5  3  6  6  4  7
  7  3  6  3  5  4  5  6  7  5  5  6  6  5  4  5  7  8  4  5  4  6  5  3
  6  3  4  7  3  6  6  6  8  5  7  6  5  5  6  6  5  6  5  4  6  4  4  6
  7  6  4  5  9  5  4  5  7  6  7  5  6  5  6  5  4  7  5  4  3  4  6  4
  4  3  7  5  3  4  4  7  6  4  5  6  8  4  4  4  5  5  4  5  4  6  2  5
  7  5  5  5  5  4  4  6  6  3  3  4  5  4  5  6  7  6  7  3  4  5  3  8
  4  1  7  4  3  3  6  1  7  4  4  5  5  8  4  6  4  7  8  5  5  5  6  3
  6  4  6  3  1  3  6  6  2  6  2  3  5  7  7  6  3  3  5  3  6  7  6  7
  4  7  5  7  4  7  5  5  6  5  3  4  3  6  2  6  3  4  5  5  5  5  2  7
  4  4  3  5  7  5 10  5  5  4  2  6  6  5  7  6  3

Каждое число в массиве означает количество успехов за 1 эксперимент.

**Биномиальное распределение** — термин в теории вероятностей и статистике, который описывает вероятность получения определённого числа успехов в серии независимых испытаний, где каждое испытание имеет два возможных исхода: успех или неудача. 